site_name: Strongbox
repo_name: 'strongbox/strongbox'
repo_url: 'https://github.com/strongbox/strongbox'
edit_uri: 'https://github.com/strongbox/strongbox-docs/edit/master/docs'
use_directory_urls: false
theme:
  name: 'material'
  custom_dir: 'theme'
  logo: ''
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  language: en
  features:
    - tabs

extra_css:
  - 'assets/stylesheets/style.css'

extra_javascript:
  - 'assets/javascripts/medium-zoom.min.js'
  - 'assets/javascripts/main.js'

plugins:
  - search
  - markdownextradata
  - git-revision-date

extra:
  url: &url !!python/object/apply:os.getenv ["DEPLOY_URL", "http://localhost:8000"]
  assetsPath: &assetsPath "assets/"
  resourcesPath: &resourcesPath !!python/object/apply:urllib.parse.urljoin [*assetsPath, "resources"]
  assets: !!python/object/apply:urllib.parse.urljoin [*url, *assetsPath]
  resources: !!python/object/apply:urllib.parse.urljoin [*url, *resourcesPath]
  repo_url: "https://github.com/strongbox/strongbox"

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_gh_links

# Page tree
nav:
  - Introduction: index.md
  - Release notes: release-notes.md
  - Contributing: contributing.md
  - License: license.md

  - User guide:
    - Getting started: user-guide/getting-started.md
    - Configuration Files:
      - The strongbox.yaml file: user-guide/configuration-files/strongbox-yaml.md
      - The strongbox-authorization.yaml file: user-guide/configuration-files/strongbox-authorization-yaml.md
      - The strongbox-cron-tasks.yaml file: user-guide/configuration-files/strongbox-cron-tasks-yaml.md
      - The strongbox-security-users.yaml file: user-guide/configuration-files/strongbox-security-users-yaml.md
    - Application properties: user-guide/application-properties.md
    - Directory structure: user-guide/directory-structure.md
    - Upgrading: user-guide/upgrading.md
    - User Interface:
      - Browsing: user-guide/ui/browsing.md
      - Global settings: user-guide/ui/global-settings.md
      - User management: user-guide/ui/user-management.md
      - Storage management: user-guide/ui/storage-management.md
      - System Information: user-guide/ui/system-information.md
      - Default URL and Credentials: user-guide/ui/default-url-users.md
    - AQL (search): user-guide/artifact-query-language.md
    - Artifact Routing Rules: user-guide/artifact-routing-rules.md
    - REST API: user-guide/rest-api.md
    - Tool Integration:
      - Ant + Ivy Example: user-guide/tool-integration/ant-ivy-example.md
      - Gradle Example: user-guide/tool-integration/gradle-example.md
      - Maven Example: user-guide/tool-integration/maven-example.md
      - NPM Example: user-guide/tool-integration/npm-example.md
      - Nuget + Chocolatey Example: user-guide/tool-integration/nuget-chocolatey-example.md
      - Nuget + Mono Example: user-guide/tool-integration/nuget-mono-example.md
      - Nuget + Visual Studio Example: user-guide/tool-integration/nuget-visual-studio-example.md
      - PyPi Example: user-guide/tool-integration/pypi-example.md
      - SBT Example: user-guide/tool-integration/sbt-example.md
      - Yarn Example: user-guide/tool-integration/yarn-example.md
  - Developer guide:
    - Introduction: developer-guide/index.md
    - Getting started: developer-guide/getting-started.md
    - Building:
      - Building the code: developer-guide/building-the-code.md
      - Building the code (Docker): developer-guide/building-the-code-with-docker.md
      - Building Strongbox using a Strongbox instance: developer-guide/building-strongbox-using-strongbox-instance.md
    - IDE setup:
      - Eclipse: developer-guide/ide-setup/eclipse.md
    - Project structure: developer-guide/project-structure.md
    - Writing code:
      - Coding convention: developer-guide/coding-convention.md
      - Getting started with persistence: developer-guide/getting-started-with-persistence.md
      - Writing controllers: developer-guide/how-to-implement-spring-controllers.md
      - Events API: developer-guide/using-the-event-api.md
      - Layout providers:
        - Writing a layout provider: developer-guide/layout-providers/how-to-implement-your-own-repository-format.md
        - Implemented providers:
          - Maven Layout Provider: developer-guide/layout-providers/maven-2-layout-provider.md
          - NPM Layout Provider: developer-guide/layout-providers/npm-layout-provider.md
          - NuGet Layout Provider: developer-guide/layout-providers/nuget-layout-provider.md
          - Raw Layout Provider: developer-guide/layout-providers/raw-layout-provider.md
      - Metadata:
        - Maven Metadata: developer-guide/metadata/maven-metadata.md
        - NPM Metadata: developer-guide/metadata/npm-metadata.md
      - Logging: developer-guide/add-logging.md
      - Search Providers: developer-guide/search-providers.md
      - Maven Indexer: developer-guide/maven-indexer.md
      - Writing custom authenticator: developer-guide/how-to-implement-a-custom-authenticator.md
      - Inspecting Hazelcast: developer-guide/how-to-inspect-a-hazelcast-cache.md
    - Upgrading Dependencies And Plugins: developer-guide/upgrading-dependencies-and-plugins.md
    - Using Git:
      - Rebasing vs Merging: developer-guide/git/rebase-vs-merge.md
    - Writing tests:
      - Getting started: developer-guide/writing-tests.md
      - JUnit: developer-guide/junit-user-guide.md
      - AssertJ: developer-guide/assertj-user-guide.md
      - Web Form Tests: developer-guide/writing-web-form-tests.md
      - Web Integration Tests: developer-guide/writing-web-integration-tests.md
    - How To Gather Requirements: developer-guide/how-to-gather-requirements.md

  - Knowledge Base:
    - Artifact Coordinates: knowledge-base/artifact-coordinates.md
    - Artifact Coordinate Validators:
      - Generic: knowledge-base/artifact-coordinate-validators/artifact-coordinate-validators.md
      - Maven: knowledge-base/artifact-coordinate-validators/artifact-coordinate-validators-maven.md
    - Layout Providers: knowledge-base/layout-providers.md
    - Repositories: knowledge-base/repositories.md
    - Storages: knowledge-base/storages.md

  - Hackfests:
    - Hackfest Guidelines: hackfests/index.md
    - Grace Hopper Celebration:
      - About Grace Hopper Celebration: hackfests/grace-hopper-celebration/index.md
      - Grace Hopper Opensource Day (2020): hackfests/grace-hopper-celebration/ghc-osd-2020.md
    - Hacktoberfest: hackfests/hacktoberfest/index.md

  - Join chat:
    - Join chat: chat-redirect.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
